name: Docker Build deploy
on:
  push:
    branches: [ main ]

env:
   DEPLOYMENT_NAME: ctse-order
   PROJECT_ID: ${{ secrets.GKE_PROJECT }}
   GKE_CLUSTER: github-actions-order
   GKE_ZONE: us-central1-c

#env:
#  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
#  GKE_CLUSTER: github-actions-customer
#  GKE_ZONE: us-central1-c
#  DEPLOYMENT_NAME: github-actions-customer-deployment
#  IMAGE: github-actions-customer-image
jobs:
  setup-build-publish:
    name: Setup build and setup-build-publish
    runs-on: ubuntu-latest
    
    steps:
     - run: echo "Build Started"
     - name: checkoout repository     
       uses: actions/checkout@v3
     - run: echo "Repository cloned to Ubuntu" 

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

     - name: Set up QEMU   
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx  
       uses: docker/setup-buildx-action@v2
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DEPLOYMENT_NAME }}:${{ github.sha }}

  deploy:
    needs: setup-build-publish
    name: deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment Started"  

      #Checkout application to deploy
      - name: Checkout repository
        uses: actions/checkout@v3

      #Authencate GCP    
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"  
      
      #Deploy 
      - name: Deploy
        run: |-
          kubectl apply -f deployment.yaml -f service.yaml
          kubectl set image deployment/$DEPLOYMENT_NAME github-actions-customer=lakindu23/ctse-customer:${{ github.sha }}
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide